### ISSUE TITLE
Getting stop code "Inaccessible boot device" on startup

### ISSUE THREAD

**Issue by ghost** [jdhitsolutions/Gen2Tools#1]
Hi Jeff,

thx for your scripts to make this complicated partition layout very easily. But I can't get my second generation vm booting. If I boot up, it ends in a blue screen loop with the stop code: Inaccessible boot device

Build/host system: Windows 10 x64 1607 LTSB
install.wim: same

`New-Gen2Disk -Path "D:\Test.vhdx" -Size 64GB`

`Set-Gen2Partition -Path "D:\Test.vhdx" -WIMPath "D:\install.wim" -Verbose`

Do you have any idea?

**Comment by ghost** [comment]
Hmm, tested it again with Server 2016 RTM and it works, seems to be an issue with (my) windows 10 image. Closing this.

**Comment by jdhitsolutions** [comment]
Glad you worked it out. You can also run into a similar issue if you create a Gen 2 disk but use it on an IDE controller. Needs to be SCSI.
